### ISSUE TITLE
upgrade-id is marked as optional but is required

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#108]
We can either default it to a value or mark it as required. I have no preference in the direction this goes so long as the tool's help is consistent with its behavior.

Right now we end up with a stack trace when the upgrade-id (marked optional) is omitted.

**Comment by ncdc** [comment]
If we keep it optional and don't do any additional work, I think it will be hard for automated systems to resume an upgrade because we don't return structured output to the caller with an easily identifiable field for the upgrade id. Maybe we should punt on that and just require an upgrade id? We can even loosen the numeric restriction and allow anything alphanumeric?

**Comment by williamsandrew** [comment]
I think requiring the upgrade-id would be fine. Our team is already specifying an ID when we attempt upgrades.

**Comment by imikushin** [comment]
Requiring Upgrade ID is good!
