### ISSUE TITLE
MachineSpec Version field is required

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#109]
As a prerequisite to using this tool, the `version` field on the control plane machines must be filled out. They are optional fields today but if not filled out this tool returns an error.

**Comment by detiber** [comment]
This gets a bit funky if imageIds are used, since they might not align with the versions specified in the version field.

**Comment by ncdc** [comment]
With the current code, we need this field to be populated to determine if we're doing a minor version upgrade. This is because we may need to create the kubelet configmap and set up rbac for it. Although maybe we should just change that logic to be "find or create"?

I don't think requiring this field will be an issue. For infra providers that do image id lookups, they can use machine.spec.version. Otherwise, we'll support full flexibility of being able to update infra and kubeadm resources once #105 merges (including image ids). WDYT?

**Comment by detiber** [comment]
Works for me

**Comment by ncdc** [comment]
To expand a bit on version:

1. We check for `kubelet-configmap-$major.$minor`, where `$major` and `$minor` come from the input to the upgrade tool
1. If it doesn't exist, we grab the _n-1_ version from the apiserver, copy it, and create it as _n_

We only do this after checking if it is in fact a minor version upgrade, which we determine by comparing the version input to the tool with the lowest machine.spec.version set in all the control plane machines. I think we can completely eliminate this logic and retain only the "find or create" code.

**Comment by ncdc** [comment]
Which is a long way of saying we can remove all the code that looks at machine.spec.version
