### ISSUE TITLE
construction of new machine name conflicts with hostname standards

### ISSUE THREAD

**Issue by ntfrnzn** [vmware/cluster-api-upgrade-tool#146]
the upgrade suffix of `.upgrade.` conflicts with the cloud-init standards

* https://linux.die.net/man/1/hostname
* https://github.com/canonical/cloud-init/blob/0469f70c8fde69cfbcbc7181a69964aafba50bbc/cloudinit/sources/__init__.py#L555-L614

Since everything after the first "." is discarded, the replacement machine ends up with the same hostname as the original and leads to problems with etcd membership.

**Comment by ncdc** [comment]
Out of curiosity, what Cluster API provider are you using?

**Comment by ncdc** [comment]
The logic in the tool currently tries to find a machine named like `whatever.upgrade.123456`, matching on `.upgrade*`. It then generates a replacement machine name with the new upgrade ID, e.g. `whatever.upgrade.999999`.

Would it be more useful to require that the user supply a machine name prefix along with the upgrade id, and the tool could construct new machine names from those values, instead of trying to do find & replace? For example:

- Original machine name: doesn't matter
- Prefix: `controlplane-`
- Upgrade id: `1234567890`
- New machine names:
    - `controlplane-1234567890-<some random suffix 1>`
    - `controlplane-1234567890-<some random suffix 2>`
    - `controlplane-1234567890-<some random suffix 3>`

Or maybe just rename upgrade id to machine prefix (so instead of supplying `controlplane-` and `1234567890` separately, you'd just supply them together as a single value)?

cc @andrewsykim @williamsandrew - WDYT?

**Comment by ntfrnzn** [comment]
Using CAPV.  And a few very simple code changes like
```
 func upgradeSuffix(upgradeID string) string {
-       return ".upgrade." + upgradeID
+       return "-upgrade-" + upgradeID
 }
```
got me past the issue. (also the regexp change)

**Comment by aaroniscode** [comment]
> The logic in the tool currently tries to find a machine named like `whatever.upgrade.123456`, matching on `.upgrade*`. It then generates a replacement machine name with the new upgrade ID, e.g. `whatever.upgrade.999999`.
> 
> Would it be more useful to require that the user supply a machine name prefix along with the upgrade id, and the tool could construct new machine names from those values, instead of trying to do find & replace? For example:
> 
> * Original machine name: doesn't matter
> * Prefix: `controlplane-`
> * Upgrade id: `1234567890`
> * New machine names:
>   
>   * `controlplane-1234567890-<some random suffix 1>`
>   * `controlplane-1234567890-<some random suffix 2>`
>   * `controlplane-1234567890-<some random suffix 3>`
> 
> Or maybe just rename upgrade id to machine prefix (so instead of supplying `controlplane-` and `1234567890` separately, you'd just supply them together as a single value)?
> 
> cc @andrewsykim @williamsandrew - WDYT?

@ncdc Really like this approach. My customer doesn't like having "upgrade" become a part of the permanent name.  I would agree that your last suggestion about not having a hard-coded prefix as some customers may want a different prefix than `controlplane`

**Comment by ncdc** [comment]
@aaroniscode to clarify, I wasn't suggested hardcoding `controlplane` anywhere - that would be a user-supplied value.

**Comment by ncdc** [comment]
@detiber @randomvariable @vincepri do you have any thoughts here?

**Comment by williamsandrew** [comment]
This seems fine. Quick question, in your example above is the random suffix still the ordinal of the control plane machine or is it truly a random value such as `7r2b2`?

**Comment by detiber** [comment]
I think my thought is that it should probably be an anti-pattern that the Machine (or Infrastructure-specific machine resource) name is used as the actual hostname of the backing instance.

That said, I would expect the name to appear as part of the generated instance within the provider's API and/or console, so I think having a way to generate names that do not reference `upgrade`, and the idea of being able to provide some type of a user-provided prefix sounds good to me.

**Comment by ncdc** [comment]
Ok, I can do a PR to replace "upgrade ID" with "machine prefix". I'd probably use that for `metadata.generateName` so the apiserver could add the random suffixes. Does that sound reasonable?

**Comment by ncdc** [comment]
@williamsandrew it would be truly random. I don't think there's any way to deterministically and accurately preserve the ordinal.

**Comment by ncdc** [comment]
Hmm this may not be as easy as I initially thought. Given an original machine as input, we are able to deterministically generate the name for its replacement machine. Changing to a machine name prefix where the replacement names are unpredictable will make the idempotency logic a lot trickier. Need to think on this some more.

**Comment by ncdc** [comment]
Instead of forcing `.upgrade.` or `-upgrade-`, or doing a machine prefix, what if we used a suffix that would two dashes followed by the upgrade ID?

For an original machine named `controlplane-0`, and an upgrade ID of `1`, the new name would be `controlplane-0--1`. Would that mess up anything in cloud init or with the hostname?

**Comment by akutz** [comment]
I just tested this with a local, CentOS machine image. Here are the results:

* Double dashes work
* The only issue I saw was with the /etc/hosts file. It used to be:

    ```shell
    ::1         ipv6-localhost ipv6-loopback
    127.0.0.1   localhost capi--00.vm
    ```

  This made it such that `hostname -f` emitted `localhost` and `hostname -d` emitted nothing. 
* It worked fine after I updated the file to:

    ```shell
    ::1         ipv6-localhost ipv6-loopback
    127.0.0.1   localhost 
    127.0.0.1   capi--00.vm
    ```

* Fixing the above issue would need to occur at the infrastructure provider level since CABPK does not currently handle the host name (https://github.com/kubernetes-sigs/cluster-api/issues/1579) or write `/etc/hosts` (https://github.com/kubernetes-sigs/cluster-api/issues/1580).
