### ISSUE TITLE
Upgrade failure not resumable after node creation timed out

### ISSUE THREAD

**Issue by williamsandrew** [vmware/cluster-api-upgrade-tool#78]
While performing an upgrade of a cluster with a 3 node control plane, the cluster upgrade tool timed out while waiting for a new machine. The error message is below:

```
Error: timed out waiting for matching node: timed out waiting for the condition
timed out waiting for the condition
timed out waiting for matching node
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*MachineCreator).waitForMatchingNode
        /workspace/pkg/upgrade/machine_creator.go:198
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*MachineCreator).NewMachine
        /workspace/pkg/upgrade/machine_creator.go:121
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).updateMachines
        /workspace/pkg/upgrade/control_plane.go:295
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).Upgrade
        /workspace/pkg/upgrade/control_plane.go:101
main.upgradeCluster
        /workspace/main.go:113
main.main.func1
        /workspace/main.go:37
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main
        /workspace/main.go:81
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

The problem is that I'm unable to resume this failed upgrade. After this failure, every subsequent run will also fail with the following error:

```
time="2019-10-02T17:43:33Z" level=info msg="Updating provider IDs to nodes"
time="2019-10-02T17:43:33Z" level=info msg="etcdctl stdout: {\"header\":{\"cluster_id\":12274807018475341212,\"member_id\":5631729273476060830,\"raft_term\":12},\"members\":[{\"ID\":5631729273476060830,\"name\":\"ip-10-0-1-221.us-west-2.compute.internal\",\"peerURLs\":[\"https://10.0.1.221:2380\"],\"clientURLs\":[\"https://10.0.1.221:2379\"]},{\"ID\":9383203200922539889,\"name\":\"ip-10-0-5-216.us-west-2.compute.internal\",\"peerURLs\":[\"https://10.0.5.216:2380\"],\"clientURLs\":[\"https://10.0.5.216:2379\"]},{\"ID\":13814063600145251805,\"name\":\"ip-10-0-3-16.us-west-2.compute.internal\",\"peerURLs\":[\"https://10.0.3.16:2380\"],\"clientURLs\":[\"https://10.0.3.16:2379\"]}]}\n"
time="2019-10-02T17:43:33Z" level=info msg="etcdctl stderr: "
time="2019-10-02T17:43:33Z" level=info msg="Couldn't retrieve oldNode" id="aws:////i-07af0e8f5bd13d4aa"
unknown previous node "aws:////i-07af0e8f5bd13d4aa"
Error: unknown previous node "aws:////i-07af0e8f5bd13d4aa"
```

Full logs are below: 

[phase1-ajw-upgrade-ha-68vfr.log](https://github.com/vmware/cluster-api-upgrade-tool/files/3686908/phase1-ajw-upgrade-ha-68vfr.log)
[phase1-ajw-upgrade-ha-2dx4s.log](https://github.com/vmware/cluster-api-upgrade-tool/files/3686909/phase1-ajw-upgrade-ha-2dx4s.log)

The following arguments were passed to the upgrade tools:

```
        - --kubernetes-version=1.15.3
        - --scope=control-plane
        - --cluster-name=ajw-upgrade-ha
        - --cluster-namespace= 2af7b66e2668ce0283f346968cbd71c986ed9fab
        - --kubeconfig-secret=ajw-upgrade-ha-kubeconfig
        - --upgrade-id=ajw-upgrade-ha-phase1
```

**Comment by ncdc** [comment]
Also cc @chuckha - you originally added the annotation in https://github.com/vmware/cluster-api-upgrade-tool/commit/d34449b91aa9fe097d8b83b4281acdbb2c271bcf

**Comment by chuckha** [comment]
I agree with your assessment, but I'd be hesitant to move the annotation earlier in the process. The annotation was originally used to convey the message "we have upgraded this machine". To that end, it should only be applied after the upgrade is successful, not before. This allowed us to skip past it when we iterated over machines. 

I believe over the course of moving to v1a2 the meaning of the annotation has changed. However, taking #79 into account, we should consider using a new set of annotations as state and forego the previous annotation we had all together. The new world that takes #78 and #79 into account and other edge cases would be something like:

* An upgrade starts and looks at all the objects it will need to modify/builds a state of the world 
* Does the upgrades while marking progress as annotations along the way
* At the end there could be an annotation around "upgrade completed successfully" or all annotations could be cleared

The single annotation is not sufficient to catch these edge cases. Reminder to those reading because I had to derive this from memory: we cannot use the k8s version as a measurement of upgrade-completion because we may have upgraded the underlying machine image and not the k8s version (think security fix).
